name: update NYT stats

on:
  schedule:
    - cron: "0 10 * * *"
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: set up python and install dependencies
      run: |
        python -m venv $HOME/myenv
        source $HOME/myenv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: fetch stats and update README
      run: |
        source $HOME/myenv/bin/activate
        python fetch_stats.py
        python update_readme.py

    - name: commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md nyt_stats_graph.png nyt_stats.json
        if ! git diff --cached --quiet; then
          git commit -m "Update NYT Stats"
          git push https://x-access-token:$GITHUB_TOKEN@github.com/aimeekco/nyt-games-widget.git HEAD:main
        else
          echo "No changes to commit."
        fi